# Artificial Neural Network

### Importing the libraries

In [85]:
import numpy as np
import pandas as pd
import tensorflow as tf
import pickle

In [86]:
tf.__version__

'2.12.0'

In [87]:
np.__version__

'1.24.4'

In [88]:
pd.__version__

'2.0.2'

## Part 1 - Data Preprocessing

### Importing the dataset

In [89]:
dataset = pd.read_csv('evaluation.csv')
#X is the data except the last column
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [90]:
print(X)

[[ 0.33333333 -1.          0.        ]
 [ 1.         -1.          0.        ]
 [ 2.          0.          0.        ]
 ...
 [ 0.66666667  2.          1.        ]
 [ 1.33333333  2.          1.        ]
 [ 1.33333333  2.          1.        ]]


In [91]:
print(y)

[0 0 0 ... 1 1 1]


### Splitting the dataset into the Training set and Test set

In [92]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [93]:
X_train

array([[0.66666667, 0.        , 0.        ],
       [0.66666667, 0.        , 0.        ],
       [1.33333333, 0.        , 0.        ],
       ...,
       [1.33333333, 0.        , 0.        ],
       [0.        , 0.        , 0.        ],
       [0.66666667, 0.        , 0.        ]])

### Feature Scaling

In [94]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [95]:
X_train

array([[-0.84997249, -0.34874595, -0.46824282],
       [-0.84997249, -0.34874595, -0.46824282],
       [ 0.0477402 , -0.34874595, -0.46824282],
       ...,
       [ 0.0477402 , -0.34874595, -0.46824282],
       [-1.74768519, -0.34874595, -0.46824282],
       [-0.84997249, -0.34874595, -0.46824282]])

In [96]:
y_train

array([0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1,
       1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0,

## Part 2 - Building the ANN

### Initializing the ANN

In [97]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [98]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the second hidden layer

In [99]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the output layer

In [100]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

## Part 3 - Training the ANN

### Compiling the ANN

In [101]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

### Training the ANN on the Training set

In [102]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100


29/29 [==============================] - 2s 3ms/step - loss: 0.6962 - accuracy: 0.4364
Epoch 2/100
29/29 [==============================] - 0s 3ms/step - loss: 0.6416 - accuracy: 0.5680
Epoch 3/100
29/29 [==============================] - 0s 3ms/step - loss: 0.5958 - accuracy: 0.7303
Epoch 4/100
29/29 [==============================] - 0s 3ms/step - loss: 0.5534 - accuracy: 0.7336
Epoch 5/100
29/29 [==============================] - 0s 3ms/step - loss: 0.5146 - accuracy: 0.7336
Epoch 6/100
29/29 [==============================] - 0s 3ms/step - loss: 0.4794 - accuracy: 0.7346
Epoch 7/100
29/29 [==============================] - 0s 3ms/step - loss: 0.4436 - accuracy: 0.7939
Epoch 8/100
29/29 [==============================] - 0s 3ms/step - loss: 0.4053 - accuracy: 0.8904
Epoch 9/100
29/29 [==============================] - 0s 3ms/step - loss: 0.3648 - accuracy: 0.9112
Epoch 10/100
29/29 [==============================] - 0s 3ms/step - loss: 0.3274 - accuracy: 0.9123
Epoch 11/100
29/29 [=

## Part 4 - Making the predictions and evaluating the model

In [103]:
pickle.dump(ann, open('ann.pkl', 'wb'))

### Predicting the Test set results

In [104]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

8/8 [==============================] - 0s 2ms/step
[[0 1]
 [1 1]
 [0 1]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 1]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 

### Making the Confusion Matrix

In [105]:
dataset = pd.read_csv('realtime.csv')
#X is 2D array and get the first row
sample = dataset.iloc[0:1, :].values

#predict the result
#how to use ann_model to predict the result

In [106]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[157   0]
 [ 20  51]]


0.9122807017543859

In [107]:
dataset = pd.read_csv('realtime.csv')
#X is 2D array and get the first row
sample = dataset.iloc[0:1, :].values
sample

array([[0.66666667, 2.        , 1.        ]])

In [113]:
import pandas as pd
import joblib
import warnings

filename = 'ann.pkl'
ann_model = joblib.load(filename)
dataset = pd.read_csv('realtime.csv')

#read the second row data and convert it into 2D array
sample = dataset.iloc[:, :].values
print(sample)

result = ann_model.predict(sample)
#approximate the result to the nearest integer

print(result)




[[0.66666667 0.         0.        ]]
1/1 [==============================] - 0s 57ms/step
[[0.35671285]]


In [2]:
import pandas as pd
import csv
#read the normal.csv file
normal2 = pd.read_csv('normal.csv')

#mix the normal.csv file
normal2 = normal2.sample(frac=1).reset_index(drop=True)



NameError: name 'pd' is not defined